/**
 * level.js — Prompt Hero
 * Data semua 20 level: client, bad prompt, CRAFT hints, evaluasi.
 */

/** Definisi semua 20 level */
export const LEVELS = [
  {
    num: 1,
    name: 'Prompt Dasar',
    icon: '📝',
    theme: 'Memahami apa itu prompt',
    xpReward: 25,
    coinReward: 10,
    client: {
      avatar: '👩‍💼',
      name: 'Ibu Sari',
      message: 'Halo! Saya butuh bantuan menulis konten untuk bisnis saya. Saya menjual produk skincare organik dan ingin membuat deskripsi produk yang menarik.',
      context: 'Buat deskripsi produk skincare organik yang menarik, informatif, dan persuasif untuk calon pembeli.',
    },
    badPrompt: 'Buat konten skincare.',
    badOutput: 'Skincare adalah perawatan kulit. Ada banyak produk skincare di pasaran. Pilih yang cocok untuk kulit Anda.',
    badAnalysis: [
      'Prompt terlalu singkat dan tidak spesifik',
      'Tidak ada informasi tentang produk yang dimaksud',
      'Tidak ada tujuan yang jelas (deskripsi produk? artikel? iklan?)',
      'Tidak ada target pembaca',
    ],
    craft: {
      context: 'Produk: Serum Vitamin C Organik 30ml\nTarget: Wanita 25-40 tahun\nKeunggulan: Bahan alami, tanpa paraben, BPOM',
      role: 'Kamu adalah copywriter produk kecantikan berpengalaman yang memahami psikologi pembeli wanita.',
      action: 'Buat deskripsi produk yang highlight manfaat, bahan utama, dan call-to-action yang persuasif.',
      format: 'Deskripsi 150-200 kata\nGunakan poin-poin bullet\nTambahkan tagline yang memorable',
      test: 'Output harus membuat pembaca tertarik membeli\nSebutkan minimal 3 manfaat spesifik\nAkhiri dengan CTA yang kuat',
    },
    evaluationFocus: ['specificity', 'clarity', 'purpose'],
  },
  {
    num: 2,
    name: 'Context',
    icon: '🗺️',
    theme: 'Memberikan konteks yang kuat',
    xpReward: 25,
    coinReward: 12,
    client: {
      avatar: '👨‍🏫',
      name: 'Pak Budi (Guru SMA)',
      message: 'Saya guru Matematika SMA kelas 10. Saya butuh soal latihan Persamaan Kuadrat yang bervariasi untuk ujian semester. Murid saya banyak yang kesulitan dengan materi ini.',
      context: 'Buat soal latihan Persamaan Kuadrat untuk siswa SMA kelas 10 yang beragam tingkat kesulitannya.',
    },
    badPrompt: 'Buat soal matematika.',
    badOutput: 'Soal 1: 2 + 2 = ?\nSoal 2: 10 - 3 = ?\nSoal 3: 5 × 4 = ?',
    badAnalysis: [
      'Tidak ada konteks tingkat pendidikan (SD? SMA? Kuliah?)',
      'Tidak menyebut topik spesifik (Persamaan Kuadrat)',
      'Tidak ada tingkat kesulitan yang diminta',
      'Tidak ada jumlah soal yang jelas',
    ],
    craft: {
      context: 'Mata pelajaran: Matematika SMA Kelas 10\nTopik: Persamaan Kuadrat (ax² + bx + c = 0)\nKurikulum: Merdeka Belajar\nJumlah soal: 10 soal\nWaktu pengerjaan: 45 menit',
      role: 'Kamu adalah guru matematika SMA berpengalaman 15 tahun yang memahami pola kesulitan siswa.',
      action: 'Buat 10 soal persamaan kuadrat dengan distribusi: 3 mudah, 4 sedang, 3 sulit.',
      format: 'Format pilihan ganda (A-D)\nSertakan kunci jawaban di bagian akhir\nTambahkan petunjuk pengerjaan',
      test: 'Soal harus berkaitan konteks nyata (bukan angka abstrak)\nKunci jawaban harus benar secara matematis\nVariasi metode: faktorisasi, kuadrat sempurna, rumus ABC',
    },
    evaluationFocus: ['context', 'specificity'],
  },
  {
    num: 3,
    name: 'Role',
    icon: '🎭',
    theme: 'Memberi AI peran yang tepat',
    xpReward: 25,
    coinReward: 14,
    client: {
      avatar: '🧑‍💼',
      name: 'Mas Dika (Startup Founder)',
      message: 'Startup saya baru dapat pendanaan seed $500K. Saya mau pitch ke investor Series A bulan depan. Butuh review pitch deck saya dan saran bagaimana memperbaikinya.',
      context: 'Review dan perbaiki pitch deck startup teknologi untuk presentasi ke investor Series A.',
    },
    badPrompt: 'Review presentasi startup saya.',
    badOutput: 'Presentasi Anda terlihat bagus. Ada beberapa hal yang bisa diperbaiki. Pastikan slide-slide Anda menarik dan informatif.',
    badAnalysis: [
      'Tidak ada role/persona yang diberikan kepada AI',
      'AI tidak tahu harus menilai dari perspektif apa (investor? desainer? CMO?)',
      'Feedback terlalu generik dan tidak actionable',
      'Tidak ada kriteria evaluasi yang spesifik',
    ],
    craft: {
      context: 'Jenis bisnis: B2B SaaS untuk manajemen supply chain\nStage: Seed, akan pitch Series A\nTarget investor: VC fokus enterprise software\nTotal funding target: $3M\nMilestone: 50 enterprise clients, ARR $200K',
      role: 'Kamu adalah partner VC senior dengan 15 tahun pengalaman investasi di startup B2B SaaS. Kamu telah mereview 500+ pitch deck dan berhasil invest di 30+ startup unicorn.',
      action: 'Review pitch deck dari perspektif investor. Identifikasi kelemahan dan berikan rekomendasi spesifik yang actionable.',
      format: 'Format: Section per section (Problem, Solution, Market, Business Model, Traction, Team, Ask)\nUntuk setiap section: Rating 1-10, Kekuatan, Kelemahan, Rekomendasi perbaikan',
      test: 'Feedback harus dari perspektif investor yang ingin return tinggi\nSertakan pertanyaan yang akan ditanya investor\nBerikan contoh benchmark dari startup sukses serupa',
    },
    evaluationFocus: ['role', 'specificity', 'action'],
  },
  {
    num: 4,
    name: 'Action',
    icon: '⚡',
    theme: 'Instruksi aksi yang jelas',
    xpReward: 25,
    coinReward: 15,
    client: {
      avatar: '👩‍🍳',
      name: 'Mbak Rini (Food Blogger)',
      message: 'Saya food blogger dengan 50K followers. Mau buat konten untuk launching menu baru: Nasi Goreng Truffle. Butuh caption Instagram yang bikin orang ngiler dan viral!',
      context: 'Buat caption Instagram untuk peluncuran menu Nasi Goreng Truffle.',
    },
    badPrompt: 'Buat caption Instagram makanan.',
    badOutput: 'Makanan ini terlihat lezat! Yuk coba di restoran kami. #food #enak #mantap',
    badAnalysis: [
      'Tidak ada aksi spesifik yang diminta (berapa caption? tone-nya apa?)',
      'Tidak menyebut nama menu dan keunikannya',
      'Caption output terlalu generik',
      'Hashtag tidak relevan dan terlalu sedikit',
    ],
    craft: {
      context: 'Menu: Nasi Goreng Truffle Special\nHarga: Rp 185.000\nKeunggulan: Truffle oil impor Italia, telur ayam kampung organik, nasi Jepang premium\nAkun: @dapur_rini_official (50K followers, niche fine dining casual)\nWaktu posting: Weekend lunch 11:00-12:00',
      role: 'Kamu adalah social media strategist spesialis F&B yang pernah viralkan 20+ menu restoran dengan total reach 100M+ views.',
      action: 'Buat TIGA variasi caption Instagram:\n1. Caption storytelling emosional (hook - story - CTA)\n2. Caption provocative/FOMO (bikin penasaran)\n3. Caption informatif dengan value proposition\n\nMasing-masing caption: 150-200 karakter + 15-20 hashtag relevan',
      format: 'Format untuk tiap caption:\n[CAPTION VARIASI X]\n[Teks caption utama]\n.\n.\n.\n[Hashtag group 1] [Hashtag group 2]',
      test: 'Caption harus trigger emotion: lapar, penasaran, atau FOMO\nHook kalimat pertama harus langsung menarik perhatian\nCTA jelas: DM, order, atau visit\nHashtag: mix popular + niche + branded',
    },
    evaluationFocus: ['action', 'format', 'specificity'],
  },
  {
    num: 5,
    name: 'Format',
    icon: '📐',
    theme: 'Tentukan format output yang tepat',
    xpReward: 30,
    coinReward: 16,
    client: {
      avatar: '👨‍💻',
      name: 'Bro Kevin (Web Developer)',
      message: 'Gue lagi bikin dokumentasi API untuk tim baru. Gue butuh template README yang profesional untuk project React + Node.js gue. Harus gampang dibaca developer lain.',
      context: 'Buat template README.md profesional untuk proyek web development React + Node.js.',
    },
    badPrompt: 'Buat dokumentasi project.',
    badOutput: 'Project ini adalah website. Cara installnya: download file lalu jalankan. Butuh internet.',
    badAnalysis: [
      'Tidak ada format yang diminta (README? Wiki? PDF? Word?)',
      'Tidak ada struktur yang jelas diminta',
      'Tidak menyebut tech stack yang digunakan',
      'Output tidak bisa langsung digunakan',
    ],
    craft: {
      context: 'Project: E-Commerce Platform "TokoBakul"\nTech stack: React 18, Node.js 20, Express, MongoDB, JWT Auth\nDeployment: Docker + AWS EC2\nTeam: 5 developers\nStatus: Production-ready v1.2.0',
      role: 'Kamu adalah senior developer open-source yang maintainnya di top 100 GitHub repos dengan 10K+ stars.',
      action: 'Buat template README.md yang lengkap dan profesional mengikuti standar GitHub best practices.',
      format: 'Format Markdown dengan sections:\n# Project Title + Badges\n## Features\n## Tech Stack\n## Prerequisites\n## Installation\n## Environment Variables\n## API Documentation\n## Contributing\n## License\n\nGunakan code blocks untuk semua command\nTambahkan emoji di setiap header section',
      test: 'Developer baru harus bisa setup project dalam <30 menit\nSemua command harus bisa di-copy-paste langsung\nSertakan contoh .env file (dengan placeholder)\nBadges: build status, coverage, version, license',
    },
    evaluationFocus: ['format', 'action', 'specificity'],
  },
  {
    num: 6,
    name: 'Test Criteria',
    icon: '✅',
    theme: 'Tentukan kriteria keberhasilan',
    xpReward: 30,
    coinReward: 18,
    client: {
      avatar: '👩‍🔬',
      name: 'Dr. Amalia (Peneliti)',
      message: 'Saya peneliti bidang kesehatan masyarakat. Butuh artikel ilmiah populer tentang manfaat puasa intermiten untuk jurnal online kampus. Harus akurat tapi tetap mudah dipahami masyarakat awam.',
      context: 'Buat artikel ilmiah populer tentang intermittent fasting untuk portal kesehatan kampus.',
    },
    badPrompt: 'Tulis artikel tentang puasa.',
    badOutput: 'Puasa adalah menahan makan dan minum. Banyak agama menganjurkan puasa. Puasa bisa membuat kita lebih sehat.',
    badAnalysis: [
      'Tidak ada kriteria kualitas yang jelas (berapa panjang? level sains apa?)',
      'Tidak ada referensi atau standar ilmiah yang diminta',
      'Tidak ada target pembaca yang jelas',
      'Output menyampur puasa agama dan medis tanpa kejelasan',
    ],
    craft: {
      context: 'Topik: Intermittent Fasting (Puasa Intermiten)\nMedia: Portal Kesehatan Kampus UI\nPembaca: Mahasiswa dan dosen (berpendidikan tapi bukan ahli nutrisi)\nPanjang: 800-1000 kata\nTujuan: Edukasi berbasis bukti ilmiah',
      role: 'Kamu adalah jurnalis sains kesehatan dengan latar belakang S2 Gizi Klinik, berpengalaman menulis untuk media seperti Kompas Kesehatan dan Halodoc.',
      action: 'Tulis artikel ilmiah populer yang: menjelaskan apa itu IF, merangkum evidence ilmiah terkini (2020-2024), dan memberikan panduan praktis.',
      format: 'Struktur artikel:\n1. Lead/Hook yang menarik\n2. Apa itu Intermittent Fasting?\n3. Bukti Ilmiah: Manfaat yang Terbukti\n4. Risiko dan Siapa yang Tidak Boleh\n5. Panduan Praktis Memulai\n6. Kesimpulan\n7. Daftar Pustaka (minimal 3 jurnal peer-reviewed)',
      test: 'KRITERIA WAJIB:\n✓ Setiap klaim harus didukung referensi jurnal (sebutkan nama jurnal/tahun)\n✓ Hindari klaim berlebihan yang tidak didukung data\n✓ Gunakan terminologi medis + penjelasan awam dalam tanda kurung\n✓ Tidak boleh menyebut IF sebagai "obat" atau "solusi ajaib"\n✓ Sertakan disclaimer medis di akhir artikel',
    },
    evaluationFocus: ['test', 'format', 'context'],
  },
  {
    num: 7,
    name: 'Framework CRAFT',
    icon: '🛠️',
    theme: 'Kuasai CRAFT secara lengkap',
    xpReward: 35,
    coinReward: 20,
    client: {
      avatar: '🧑‍💼',
      name: 'Tim Marketing (UMKM Batik)',
      message: 'Kami adalah UMKM batik dari Pekalongan. Mau buat campaign media sosial untuk target generasi muda. Banyak anak muda yang anggap batik itu "jadul". Kami ingin mengubah persepsi itu!',
      context: 'Buat strategi konten media sosial untuk UMKM batik agar relevan dengan Gen Z dan Milenial.',
    },
    badPrompt: 'Buat strategi marketing batik.',
    badOutput: 'Untuk marketing batik, Anda bisa gunakan Instagram dan TikTok. Posting foto batik yang bagus. Gunakan hashtag yang populer.',
    badAnalysis: [
      'Tidak menggunakan framework yang terstruktur',
      'Tidak ada konteks bisnis yang lengkap',
      'Strategi terlalu generik, tidak ada tactical plan',
      'Tidak ada KPI atau target yang terukur',
    ],
    craft: {
      context: 'Brand: "Batik Sejati Pekalongan" berdiri 1985\nProduk: Batik tulis & cap, harga Rp 250K-2,5M\nMasalah: 85% pembeli usia 40+, Gen Z hampir tidak ada\nBudget marketing: Rp 5 juta/bulan\nSaluran tersedia: Instagram, TikTok, WhatsApp Business',
      role: 'Kamu adalah brand strategist spesialis heritage brand yang pernah membantu brand batik Semar dan Danar Hadi menjangkau Gen Z.',
      action: 'Buat rencana konten media sosial 30 hari yang mencakup: content pillars, content calendar, format konten, tone of voice, dan KPI yang terukur.',
      format: 'Output dalam format:\n1. Brand Repositioning Statement (2-3 kalimat)\n2. Content Pillars (4 pilar dengan penjelasan)\n3. Content Calendar Minggu 1 (7 hari, platform, format, caption idea)\n4. KPI Target Bulan 1\n5. Budget Allocation',
      test: 'Strategi harus bisa dieksekusi dengan budget Rp 5 juta\nKonten harus relevan untuk usia 18-28 tahun\nHarus ada minimal 1 ide konten yang berpotensi viral\nKPI harus SMART (Specific, Measurable, Achievable, Relevant, Time-bound)\nTone: Modern tapi tetap menghargai nilai budaya batik',
    },
    evaluationFocus: ['context', 'role', 'action', 'format', 'test'],
  },
  {
    num: 8,
    name: 'Prompt Artikel',
    icon: '📰',
    theme: 'Buat artikel berkualitas tinggi',
    xpReward: 35,
    coinReward: 22,
    client: {
      avatar: '✍️',
      name: 'Redaksi Teknologi.id',
      message: 'Kami butuh artikel SEO tentang tren AI di Indonesia tahun 2025 untuk website kami. Target 1500 kata, harus muncul di halaman 1 Google untuk keyword "AI Indonesia 2025".',
      context: 'Buat artikel SEO-optimized tentang tren kecerdasan buatan di Indonesia untuk media teknologi online.',
    },
    badPrompt: 'Tulis artikel AI.',
    badOutput: 'AI adalah kecerdasan buatan. AI bisa melakukan banyak hal. Di Indonesia, AI semakin berkembang. Banyak perusahaan menggunakan AI.',
    badAnalysis: [
      'Tidak ada keyword target untuk SEO',
      'Tidak ada struktur artikel yang diminta (H1, H2, dll)',
      'Tidak ada panjang artikel yang ditentukan',
      'Konten terlalu umum tanpa data atau fakta spesifik',
    ],
    craft: {
      context: 'Media: Teknologi.id (DA 45, 200K monthly visitors)\nTarget keyword: "AI Indonesia 2025" (search volume 8.1K/bulan)\nPanjang: 1500-1800 kata\nTujuan: Rank di halaman 1 Google + edukasi pembaca\nPembaca: Profesional IT, startup founder, mahasiswa teknologi',
      role: 'Kamu adalah jurnalis teknologi senior dengan spesialisasi AI/ML yang pernah publish di TechCrunch, Wired, dan Kompas Tekno. Paham SEO on-page.',
      action: 'Tulis artikel SEO-optimized yang komprehensif tentang tren AI di Indonesia 2025 dengan data terkini.',
      format: 'Struktur SEO:\nH1: [Target keyword utama]\nMeta description: 155 karakter\nH2 (5-6): Subtopik utama\nH3: Sub-subtopik\nSetiap H2 section: 200-300 kata\nInternal linking placeholder: [LINK: kata_anchor]\nFAQ section: 3 pertanyaan + jawaban\nConclusion dengan CTA',
      test: 'Keyword density "AI Indonesia": 1-2% (jangan keyword stuffing)\nSertakan data statistik: minimal 5 data point dengan sumber\nGunakan LSI keywords: machine learning Indonesia, startup AI, digitalisasi\nReadability: skor Flesch Reading Ease >60\nSetiap section harus memberikan informasi unik dan bernilai',
    },
    evaluationFocus: ['action', 'format', 'test', 'context'],
  },
  {
    num: 9,
    name: 'Prompt Email',
    icon: '📧',
    theme: 'Email profesional yang efektif',
    xpReward: 35,
    coinReward: 22,
    client: {
      avatar: '👔',
      name: 'Bapak Hendro (Sales Manager)',
      message: 'Saya Sales Manager di perusahaan software B2B. Mau kirim cold email ke 50 CFO perusahaan manufaktur. Produk kami bisa menghemat biaya operasional mereka hingga 40%. Open rate cold email kami sekarang hanya 12%, ingin meningkat ke 30%+.',
      context: 'Buat template cold email B2B untuk menjangkau CFO perusahaan manufaktur.',
    },
    badPrompt: 'Buat email ke perusahaan.',
    badOutput: 'Dear Bapak/Ibu,\n\nPerkenalkan, kami adalah perusahaan software. Kami memiliki produk yang bagus. Silakan hubungi kami jika tertarik.\n\nTerima kasih.',
    badAnalysis: [
      'Tidak ada persona penerima yang jelas (jabatan, industri)',
      'Tidak ada value proposition yang spesifik',
      'Subject line tidak disebutkan (paling penting untuk open rate)',
      'Email terlalu generik, tidak ada hook menarik',
    ],
    craft: {
      context: 'Pengirim: Bapak Hendro, Sales Manager\nProduk: Software ERP Manufaktur "ManufactPro"\nUSP: Hemat biaya operasional 40% dalam 6 bulan (proven by 50+ clients)\nPenerima: CFO perusahaan manufaktur, 200-500 karyawan, revenue Rp 50-500M\nGoal: Schedule demo call 30 menit',
      role: 'Kamu adalah copywriter B2B email spesialis yang pernah meningkatkan cold email open rate dari 8% ke 42% untuk perusahaan SaaS enterprise.',
      action: 'Buat SATU cold email template yang:\n- Memiliki 3 variasi subject line (A/B/C test)\n- Body email: 100-150 kata\n- Personalisasi placeholder yang jelas\n- Follow-up sequence (email #2 dan #3)',
      format: 'Format:\n[SUBJECT LINE A]: ...\n[SUBJECT LINE B]: ...\n[SUBJECT LINE C]: ...\n\n[EMAIL BODY]\nHi {FirstName},\n...\n\n[FOLLOW-UP #2 - Hari ke-3]\n...\n[FOLLOW-UP #3 - Hari ke-7]\n...',
      test: 'Subject line harus <50 karakter dan menghindari spam words\nParagraf pertama harus tentang MEREKA, bukan tentang produk kita\nValue proposition harus spesifik: angka dan timeline\nCTA harus low-friction (bukan "beli" tapi "mau tau caranya?")\nGunakan bahasa formal tapi tidak kaku',
    },
    evaluationFocus: ['action', 'format', 'role'],
  },
  {
    num: 10,
    name: 'Prompt Copywriting',
    icon: '✍️',
    theme: 'Copy yang menjual',
    xpReward: 40,
    coinReward: 25,
    client: {
      avatar: '🛍️',
      name: 'Kak Fitri (Online Shop)',
      message: 'Saya jualan suplemen kesehatan online. Produk baru saya: Collagen + Vitamin C Gummy. Mau buat landing page copy yang convert! Sekarang conversion rate cuma 1.2%, target 3%+.',
      context: 'Buat landing page copy untuk suplemen Collagen + Vitamin C Gummy yang meningkatkan konversi.',
    },
    badPrompt: 'Buat iklan suplemen.',
    badOutput: 'Suplemen kami bagus untuk kesehatan Anda. Beli sekarang dan rasakan manfaatnya. Harga terjangkau!',
    badAnalysis: [
      'Tidak menggunakan framework copywriting (AIDA, PAS, dll)',
      'Tidak ada social proof atau bukti klaim',
      'Benefit terlalu generik ("bagus untuk kesehatan")',
      'Tidak ada urgency atau scarcity untuk trigger keputusan beli',
    ],
    craft: {
      context: 'Produk: "GlowUp Gummy" - Collagen 2500mg + Vitamin C 500mg\nHarga: Rp 299.000/botol (30 pcs)\nBukti klinis: Uji klinis pada 200 wanita, 89% melihat perbaikan kulit dalam 4 minggu\nSocial proof: 4.8/5 bintang dari 2,340 reviewer\nTarget: Wanita 25-40, skincare enthusiast, income menengah-atas',
      role: 'Kamu adalah copywriter conversion rate optimization (CRO) yang pernah optimasi landing page brand Hada Labo, Somethinc, dan Wardah dengan average uplift 180% konversi.',
      action: 'Buat full landing page copy menggunakan framework AIDA yang mencakup semua sections.',
      format: 'Sections yang dibutuhkan:\n1. HEADLINE utama (max 10 kata) + Subheadline\n2. Hero section: Problem agitation\n3. Product reveal + USP\n4. Benefits (6 poin dengan ikon)\n5. How it works (3 langkah)\n6. Social Proof (testimoni format)\n7. FAQ (5 pertanyaan)\n8. Guarantee section\n9. CTA final dengan urgency\n10. Footer trust badges',
      test: 'Gunakan bahasa "kamu" (conversational)\nSetiap klaim benefit harus disertai bukti/angka\nHeadline harus lulus uji: "Apa manfaatnya UNTUK SAYA?"\nGunakan power words: terbukti, garansi, eksklusif, ribuan\nHindari klaim medis yang berlebihan (BPOM compliance)\nCTA button text: bukan "Beli", tapi action yang exciting',
    },
    evaluationFocus: ['action', 'format', 'test', 'context'],
  },
  {
    num: 11,
    name: 'Prompt Image',
    icon: '🎨',
    theme: 'Prompt untuk AI image generator',
    xpReward: 40,
    coinReward: 28,
    client: {
      avatar: '🧑‍🎨',
      name: 'Kang Rian (Desainer)',
      message: 'Saya desainer grafis yang pakai Midjourney untuk klien. Klien minta ilustrasi untuk brand batik premium modern. Mau gambar yang estetik, cocok untuk packaging dan website.',
      context: 'Buat prompt Midjourney untuk ilustrasi brand batik premium modern yang cocok untuk packaging.',
    },
    badPrompt: 'gambar batik',
    badOutput: '[Bayangkan: gambar batik motif abstrak berwarna-warni, kualitas rendah, tidak ada konsep yang jelas]',
    badAnalysis: [
      'Prompt 2 kata tidak cukup mengarahkan AI image generator',
      'Tidak ada style/aesthetic yang diminta (fotografis? ilustrasi? vektor?)',
      'Tidak ada warna atau mood yang ditentukan',
      'Tidak ada aspect ratio atau resolusi untuk tujuan packaging',
    ],
    craft: {
      context: 'Penggunaan: Packaging box produk batik premium + hero image website\nBrand personality: Mewah, modern, tetap menghargai tradisi\nWarna brand: Deep indigo (#1a1a4e), gold (#d4af37), cream (#f5f0e8)\nTarget market: Kelas atas, umur 30-50, menghargai heritage',
      role: 'Kamu adalah prompt engineer spesialis Midjourney v6 yang pernah buat visual untuk brand fashion Loro Piana, Batik Semar, dan Dian Pelangi.',
      action: 'Buat 3 variasi prompt Midjourney yang berbeda pendekatan visual untuk brand batik premium.',
      format: 'Format setiap prompt:\n[PROMPT VARIASI X - Deskripsi Gaya]\n/imagine prompt: [full prompt text] --ar [ratio] --v 6 --style [style]\n\nCatatan teknis: Jelaskan pilihan parameter',
      test: 'Setiap prompt harus:\n- Memiliki subject yang jelas\n- Deskripsi style/medium spesifik\n- Color palette disebutkan\n- Mood/atmosphere terdefinisi\n- Technical parameter: --ar, --v, --style\n- Tambahkan negative prompt (--no) untuk menghindari hasil yang tidak diinginkan',
    },
    evaluationFocus: ['action', 'format', 'specificity'],
  },
  {
    num: 12,
    name: 'Prompt Video',
    icon: '🎬',
    theme: 'Prompt untuk AI video generator',
    xpReward: 40,
    coinReward: 28,
    client: {
      avatar: '📹',
      name: 'Mbak Yuni (Content Creator)',
      message: 'Saya content creator yang eksplorasi AI video untuk klien. Klien: perusahaan wisata. Butuh video promosi Bali yang cinematic, 30 detik, untuk iklan YouTube.',
      context: 'Buat prompt untuk AI video generator (Sora/Runway) untuk video promosi Bali yang cinematic.',
    },
    badPrompt: 'video bali',
    badOutput: '[Bayangkan: video blur, random scene, tidak ada narasi visual yang kohesif]',
    badAnalysis: [
      'Tidak ada durasi yang disebutkan (30 detik vs 2 menit = beda total)',
      'Tidak ada visual sequence / shot list',
      'Tidak ada style sinematografi yang diminta',
      'Tidak ada mood/tone untuk wisata mewah vs backpacker',
    ],
    craft: {
      context: 'Platform: YouTube Ads (skip setelah 5 detik)\nDurasi: 30 detik\nKlien: "Bali Luxury Retreat" - resort bintang 5\nTujuan: Awareness + trigger desire untuk booking\nTarget: Pasangan kelas atas, umur 28-45, income tinggi',
      role: 'Kamu adalah creative director video yang pernah buat campaign untuk The Ritz-Carlton, Four Seasons, dan Banyan Tree menggunakan AI video tools.',
      action: 'Buat prompt video dengan struktur shot-by-shot untuk video 30 detik menggunakan Sora/Runway Gen-3.',
      format: '[OVERVIEW]\nMood: ...\nColor grade: ...\nMusik: ...\n\n[SHOT LIST]\n00:00-00:05 | Shot 1: [deskripsi visual detail] | Camera: [gerakan kamera] | Duration: 5s\n00:05-00:10 | Shot 2: ... | ... | ...\n...\n\n[MASTER PROMPT for AI]\n"[Full cinematic prompt text, 100-150 kata]"\n\n[NEGATIVE PROMPT]\nHindari: ...',
      test: 'Shot pertama (0-5 detik) harus stop-scroll dalam 5 detik\nSetiap shot harus menyambung secara visual (continuity)\nWajib sebutkan: lighting (golden hour? blue hour?), camera movement, color palette\nGunakan cinematic terms: rack focus, dolly zoom, aerial drone, slow motion\nAkhiri dengan shot yang memorable untuk recall brand',
    },
    evaluationFocus: ['action', 'format', 'specificity'],
  },
  {
    num: 13,
    name: 'Prompt Website',
    icon: '🌐',
    theme: 'Brief website yang komprehensif',
    xpReward: 45,
    coinReward: 30,
    client: {
      avatar: '🏢',
      name: 'PT Maju Bersama',
      message: 'Kami perusahaan logistik B2B yang mau buat website baru. Target: klien korporat. Ingin terlihat profesional dan trustworthy. Butuh brief untuk tim developer dan desainer kami.',
      context: 'Buat website brief komprehensif untuk perusahaan logistik B2B yang ingin website profesional.',
    },
    badPrompt: 'Buat website perusahaan logistik.',
    badOutput: 'Website logistik harus memiliki halaman Beranda, Tentang Kami, dan Kontak. Gunakan warna biru untuk kesan profesional.',
    badAnalysis: [
      'Tidak ada spesifikasi teknis (tech stack, CMS, hosting)',
      'Tidak ada sitemap atau struktur halaman yang detail',
      'Tidak ada user journey yang didefinisikan',
      'Tidak ada komponen UI/UX yang dispecifikasi',
    ],
    craft: {
      context: 'Perusahaan: PT Maju Bersama Logistics (berdiri 2010)\nLayanan: Freight forwarding, last-mile delivery, warehouse management\nTarget klien: Perusahaan manufaktur & e-commerce (B2B)\nKompetitor: JNE Express Logistics, Anteraja Enterprise\nBudget website: Rp 150-200 juta\nTimeline: 3 bulan',
      role: 'Kamu adalah UX Director dan project manager IT yang pernah deliver 50+ project website enterprise dengan client satisfaction rate 96%.',
      action: 'Buat website brief dokumen yang bisa langsung digunakan oleh tim developer, designer, dan content writer.',
      format: 'Dokumen website brief:\n1. Executive Summary (tujuan, target pengguna, KPI)\n2. Sitemap (semua halaman + hierarchy)\n3. User Journey Map (3 persona utama)\n4. Key Pages Wireframe Description\n5. Design Guidelines (brand, warna, tipografi, komponen)\n6. Technical Requirements (tech stack, integrasi, performance)\n7. Content Requirements (per halaman)\n8. Project Timeline & Milestone\n9. Budget Breakdown\n10. Success Metrics',
      test: 'Brief harus bisa dipahami oleh: developer, designer, dan klien non-teknis\nSetiap halaman utama harus ada wireframe description minimal 5 elemen\nKPI harus terukur: load time <3 detik, mobile responsive, Core Web Vitals\nSertakan contoh website referensi untuk inspirasi design\nBerikan risk management: apa yang bisa salah dan mitigasinya',
    },
    evaluationFocus: ['context', 'action', 'format', 'test'],
  },
  {
    num: 14,
    name: 'Prompt Coding',
    icon: '💻',
    theme: 'Prompt untuk menghasilkan kode terbaik',
    xpReward: 45,
    coinReward: 32,
    client: {
      avatar: '👩‍💻',
      name: 'Mbak Dewi (Backend Dev)',
      message: 'Saya lagi build API untuk aplikasi e-commerce. Butuh endpoint untuk sistem cart yang efisien. Stack: Node.js, Express, MongoDB. Harus production-ready dengan best practices.',
      context: 'Buat prompt untuk menggenerate kode REST API cart system yang production-ready dengan Node.js.',
    },
    badPrompt: 'Buat kode cart untuk website.',
    badOutput: 'function addToCart(item) {\n  cart.push(item);\n  console.log("Added!");\n}',
    badAnalysis: [
      'Tidak ada tech stack yang disebutkan (Node? Python? PHP?)',
      'Tidak ada requirement keamanan (auth? validation?)',
      'Tidak ada error handling yang diminta',
      'Tidak ada database schema yang dijelaskan',
    ],
    craft: {
      context: 'Project: E-Commerce API "BelanjAja"\nLanguage: Node.js 20, Express 4.18\nDatabase: MongoDB dengan Mongoose\nAuth: JWT Bearer Token\nEnvironment: Production (perlu error handling ketat)\nExpected load: 10,000 req/menit peak',
      role: 'Kamu adalah senior backend engineer dengan 8 tahun pengalaman Node.js yang pernah architect sistem e-commerce Tokopedia dan Shopee skala enterprise.',
      action: 'Generate kode endpoint REST API untuk Cart System yang lengkap meliputi: tambah item, hapus item, update quantity, lihat cart, dan checkout.',
      format: 'Struktur output kode:\n1. models/Cart.js - Mongoose Schema\n2. controllers/cartController.js - Business logic\n3. routes/cart.js - Express routes\n4. middleware/validateCart.js - Input validation\n5. Postman collection JSON untuk testing\n\nSetiap file: JSDoc comments untuk setiap function',
      test: 'Kode harus include:\n✓ Input validation (Joi atau express-validator)\n✓ Error handling dengan HTTP status codes yang tepat\n✓ JWT authentication middleware\n✓ Rate limiting untuk prevent abuse\n✓ MongoDB transaction untuk operasi atomic\n✓ Unit test skeleton (Jest)\n✓ Response format konsisten: { success, data, message }\nPerformance: Query harus menggunakan index yang tepat',
    },
    evaluationFocus: ['context', 'action', 'format', 'test'],
  },
  {
    num: 15,
    name: 'Prompt Agent',
    icon: '🤖',
    theme: 'Design AI Agent yang powerful',
    xpReward: 50,
    coinReward: 35,
    client: {
      avatar: '🚀',
      name: 'Startup AgensiKu',
      message: 'Kami build platform AI Agent untuk UMKM. Butuh design agent yang bisa membantu pemilik UMKM menganalisis penjualan, memberi rekomendasi stok, dan generate laporan otomatis.',
      context: 'Design sistem AI Agent untuk membantu UMKM menganalisis bisnis dan membuat keputusan data-driven.',
    },
    badPrompt: 'Buat AI untuk bisnis.',
    badOutput: 'AI bisa membantu bisnis Anda. Gunakan chatbot untuk melayani pelanggan. AI juga bisa analisis data.',
    badAnalysis: [
      'Tidak ada definisi clear tentang kapabilitas agent',
      'Tidak ada tools/functions yang didefinisikan',
      'Tidak ada workflow atau decision tree',
      'Tidak ada data input/output yang dispecifikasi',
    ],
    craft: {
      context: 'Platform: "BisnisPintar" - AI Agent untuk UMKM\nUser: Pemilik UMKM F&B (warung, kafe, resto kecil)\nData tersedia: Data transaksi POS, inventory, supplier, customer order history\nIntegrasi: GoPay, OVO, Tokopedia, Shopee (via API)\nTech stack: GPT-4o + LangChain + Supabase',
      role: 'Kamu adalah AI Agent Architect yang pernah design sistem multi-agent untuk Bank BRI, Gojek, dan McKinsey dengan fokus SME enablement.',
      action: 'Design sistem AI Agent lengkap termasuk: agent persona, tools definition, workflow, prompt system, dan contoh use case.',
      format: 'Dokumen Agent Design:\n1. Agent Persona & Capabilities\n2. Tools/Functions Definition (dalam format function calling JSON)\n3. Agent Workflow Diagram (text-based)\n4. System Prompt (full)\n5. Sample Conversation Flow (3 skenario)\n6. Error Handling Strategy\n7. Safety Guardrails',
      test: 'Agent harus bisa menangani 3 core task:\n✓ Analisis tren penjualan (daily/weekly/monthly)\n✓ Rekomendasi restock berbasis data\n✓ Generate laporan laba-rugi sederhana\n\nSafety requirements:\n- Tidak boleh akses data di luar scope UMKM tersebut\n- Harus konfirmasi sebelum tindakan yang irreversible\n- Fallback ke human jika confidence rendah',
    },
    evaluationFocus: ['context', 'role', 'action', 'format', 'test'],
  },
  {
    num: 16,
    name: 'Context Engineering',
    icon: '🧬',
    theme: 'Rekayasa konteks tingkat lanjut',
    xpReward: 55,
    coinReward: 40,
    client: {
      avatar: '🔬',
      name: 'Dr. Tech (AI Researcher)',
      message: 'Saya riset context engineering untuk LLM. Butuh demonstrasi bagaimana merancang context window yang optimal untuk task: dokumen hukum sangat panjang (200 halaman) yang perlu dianalisis dan dirangkum.',
      context: 'Rancang strategi context engineering untuk menganalisis dokumen hukum panjang dengan LLM.',
    },
    badPrompt: 'Rangkum dokumen hukum ini.',
    badOutput: 'Dokumen ini membahas tentang hukum. Intinya ada beberapa pasal penting. Sebaiknya konsultasikan dengan pengacara.',
    badAnalysis: [
      'Tidak ada strategi untuk mengatasi limitasi context window',
      'Tidak ada chunking strategy untuk dokumen panjang',
      'Tidak ada hirarki informasi yang direncanakan',
      'Tidak ada quality control untuk output rangkuman',
    ],
    craft: {
      context: 'Dokumen: Kontrak PKS (Perjanjian Kerja Sama) antara dua korporat, 200 halaman\nLLM yang digunakan: Claude 3.5 Sonnet (200K context) atau GPT-4o (128K context)\nTujuan: Identifikasi klausul berisiko, summarize obligations, flag anomali\nPengguna akhir: Lawyer junior yang perlu review cepat',
      role: 'Kamu adalah Context Engineering specialist yang pernah build legal AI tools untuk firma hukum top SSEK Legal Consultants dan Makarim & Taira.',
      action: 'Rancang strategi context engineering end-to-end: preprocessing, chunking, retrieval, dan synthesis.',
      format: 'Delivery:\n1. Context Window Strategy (diagram text)\n2. Chunking Algorithm (pseudocode)\n3. Hierarchical Summarization Prompt (sistem prompt lengkap)\n4. Retrieval Strategy untuk pertanyaan spesifik\n5. Synthesis Prompt untuk final output\n6. Quality Check Checklist',
      test: 'Strategi harus mengatasi: dokumen > context window limit\nChunking harus preserve: struktur pasal, cross-references, definisi\nOutput akhir harus terstruktur: Parties, Obligations, Rights, Penalties, Termination\nHarus ada confidence score untuk setiap extracted information\nLatency requirement: full analysis dalam <5 menit',
    },
    evaluationFocus: ['context', 'action', 'format', 'test'],
  },
  {
    num: 17,
    name: 'Memory',
    icon: '🧠',
    theme: 'Sistem memori untuk AI',
    xpReward: 55,
    coinReward: 42,
    client: {
      avatar: '💭',
      name: 'Tim Product (EdTech)',
      message: 'Kami build AI tutor personal. Masalah: AI lupa tentang murid setelah sesi berakhir. Butuh sistem memori yang membuat AI ingat preferensi, progress, dan kelemahan setiap murid.',
      context: 'Design sistem memori untuk AI tutor personal yang personalisasi pengalaman belajar setiap murid.',
    },
    badPrompt: 'Buat AI yang ingat user.',
    badOutput: 'Anda bisa gunakan database untuk menyimpan data user. Simpan nama dan preferensi mereka.',
    badAnalysis: [
      'Tidak ada arsitektur memori yang didesign',
      'Tidak ada kategori memori (short-term vs long-term)',
      'Tidak ada strategi retrieval yang efisien',
      'Tidak ada privacy consideration',
    ],
    craft: {
      context: 'Platform: "PintarAI" - Tutor AI untuk pelajar SMP-SMA\nLearning subjects: Matematika, Fisika, Bahasa Indonesia\nData yang perlu diingat: Gaya belajar, level pemahaman per topik, kesalahan berulang, jadwal belajar, motivasi/demotivasi triggers\nSkala: 100,000 murid aktif',
      role: 'Kamu adalah Memory Systems Architect yang design cognitive memory framework untuk AI tutoring di Khan Academy dan Duolingo.',
      action: 'Design sistem memori multi-layer untuk AI tutor personal yang persist antar sesi.',
      format: 'System Design Document:\n1. Memory Architecture (4 layer: working, episodic, semantic, procedural)\n2. Memory Schema (JSON structure)\n3. Memory Update Prompt (kapan & bagaimana update)\n4. Memory Retrieval Strategy\n5. System Prompt template dengan memory injection\n6. Privacy & Data Governance\n7. Memory Compression Strategy (untuk long-term users)',
      test: 'Sistem harus:\n✓ Ingat kelemahan spesifik murid per subtopik\n✓ Adaptasi style penjelasan sesuai preferensi murid\n✓ Track progress dan celebrate milestones\n✓ Tidak menyebut data sensitif di sesi publik/grup\n\nPerformance:\n- Memory retrieval < 200ms\n- Storage efficient (maksimal 10KB per murid per bulan)\n- GDPR/UU PDP Indonesia compliant',
    },
    evaluationFocus: ['context', 'role', 'action', 'format'],
  },
  {
    num: 18,
    name: 'RAG',
    icon: '📚',
    theme: 'Retrieval Augmented Generation',
    xpReward: 60,
    coinReward: 45,
    client: {
      avatar: '🏛️',
      name: 'Kemendikbud Digital',
      message: 'Kami bangun AI asisten untuk guru yang bisa menjawab pertanyaan berdasarkan kurikulum Merdeka Belajar resmi. Butuh sistem RAG yang akurat dan tidak halusinasi.',
      context: 'Design sistem RAG untuk AI asisten kurikulum Merdeka Belajar yang akurat dan anti-halusinasi.',
    },
    badPrompt: 'Buat chatbot untuk kurikulum.',
    badOutput: 'Chatbot bisa menjawab pertanyaan tentang kurikulum. Masukkan semua dokumen ke database lalu AI bisa menjawab.',
    badAnalysis: [
      'Tidak ada pipeline RAG yang terstruktur',
      'Tidak ada embedding dan indexing strategy',
      'Tidak ada anti-hallucination guardrail',
      'Tidak ada evaluation metric untuk akurasi',
    ],
    craft: {
      context: 'Knowledge Base: 500+ dokumen kurikulum Merdeka Belajar (modul ajar, CP, ATP, TP)\nFormat dokumen: PDF, DOCX, Excel\nSkala: 3 juta guru di Indonesia\nCritical requirement: TIDAK BOLEH halusinasi (informasi kurikulum harus 100% akurat)\nBahasa: Indonesia + beberapa daerah (Jawa, Sunda)',
      role: 'Kamu adalah RAG System Architect yang pernah build knowledge system untuk pemerintah Federal Jerman dan Ministry of Education Singapore.',
      action: 'Design end-to-end RAG pipeline yang production-ready dengan anti-hallucination system.',
      format: 'Technical Design:\n1. Document Preprocessing Pipeline\n2. Chunking Strategy (dengan size, overlap specs)\n3. Embedding Model Choice & Rationale\n4. Vector Database Schema (Pinecone/Chroma/Weaviate)\n5. Retrieval Strategy (semantic + keyword hybrid)\n6. Re-ranking Algorithm\n7. Augmented Generation Prompt\n8. Anti-Hallucination Guardrails\n9. Citation & Grounding System\n10. Evaluation Framework (RAGAS metrics)',
      test: 'Pipeline harus achieve:\n✓ Retrieval Recall@5 > 90%\n✓ Answer Faithfulness > 95% (tidak ada info yang tidak ada di dokumen)\n✓ Latency P95 < 3 detik\n✓ Fallback: "Saya tidak menemukan informasi ini dalam kurikulum resmi"\n\nHalusinasi Prevention:\n- Source attribution wajib (sebutkan dokumen + halaman)\n- Confidence threshold: tidak menjawab jika similarity < 0.75\n- Human review flag untuk pertanyaan edge case',
    },
    evaluationFocus: ['context', 'action', 'format', 'test'],
  },
  {
    num: 19,
    name: 'MCP',
    icon: '🔌',
    theme: 'Model Context Protocol',
    xpReward: 60,
    coinReward: 48,
    client: {
      avatar: '⚙️',
      name: 'CTO Startup FinTech',
      message: 'Kami mau integrate Claude ke dalam ekosistem tools kami menggunakan MCP. Tools yang perlu diintegrasikan: database pelanggan, sistem pembayaran, dan analytics dashboard. Butuh design MCP server.',
      context: 'Design MCP server untuk mengintegrasikan Claude dengan ekosistem tools FinTech perusahaan.',
    },
    badPrompt: 'Buat integrasi AI dengan database.',
    badOutput: 'Anda bisa hubungkan AI dengan database menggunakan API. Buat endpoint lalu panggil dari AI.',
    badAnalysis: [
      'Tidak memahami MCP protocol dan cara kerjanya',
      'Tidak ada tool definition yang proper',
      'Tidak ada keamanan/security untuk akses finansial',
      'Tidak ada error handling untuk transaksi',
    ],
    craft: {
      context: 'Perusahaan: "PayCepat" - Payment gateway & wallet B2B\nTools yang ada: PostgreSQL (customer DB), Xendit API (payment), Metabase (analytics)\nUse case: Claude membantu tim internal untuk: query data pelanggan, check status transaksi, generate laporan\nSecurity: Data keuangan, harus SOC2 + OJK compliant\nTech: TypeScript, Node.js',
      role: 'Kamu adalah MCP Protocol expert yang pernah implement MCP untuk Stripe, Plaid, dan beberapa neobank Asia Tenggara.',
      action: 'Design dan buat implementasi MCP server lengkap untuk ekosistem PayCepat.',
      format: 'Deliverables:\n1. MCP Server Architecture Diagram\n2. Tool Definitions (JSON Schema) untuk:\n   - query_customers (PostgreSQL)\n   - check_transaction_status (Xendit)\n   - get_analytics_report (Metabase)\n3. Implementation Code (TypeScript skeleton)\n4. Security Layer Design\n5. Error Handling Strategy\n6. Rate Limiting & Quota Management\n7. Audit Logging Schema\n8. Claude System Prompt untuk menggunakan tools ini',
      test: 'Security requirements:\n✓ PII data masking (no raw card numbers/KTP in Claude context)\n✓ Role-based access (CS bisa query, Finance bisa approve)\n✓ Every tool call logged untuk audit trail\n✓ Rate limit: max 100 calls/user/jam\n\nReliability:\n- Timeout handling per tool\n- Graceful degradation jika tool down\n- Idempotency untuk write operations',
    },
    evaluationFocus: ['context', 'role', 'action', 'format', 'test'],
  },
  {
    num: 20,
    name: 'Final Boss: Master Prompt Engineer',
    icon: '👑',
    theme: 'Gabungkan semua yang kamu pelajari',
    xpReward: 100,
    coinReward: 100,
    client: {
      avatar: '🌐',
      name: 'CEO AI Startup',
      message: 'Selamat datang, Prompt Hero. Ini adalah misi final. Buat prompt master untuk membangun sistem AI complete untuk UMKM Indonesia: dari onboarding, analisis bisnis, rekomendasi AI, hingga laporan otomatis. Kalahkan virus GENERIC OUTPUT untuk selamanya!',
      context: 'MISI FINAL: Design prompt master yang komprehensif untuk sistem AI terintegrasi bagi UMKM Indonesia.',
    },
    badPrompt: 'Buat AI untuk UMKM.',
    badOutput: 'AI bisa membantu UMKM Anda berkembang. Gunakan chatbot untuk layanan pelanggan. AI juga bisa analisis data penjualan Anda.',
    badAnalysis: [
      'Ini adalah virus GENERIC OUTPUT dalam bentuk paling parah!',
      'Tidak ada spesifisitas apapun tentang sistem yang dibutuhkan',
      'Tidak ada arsitektur solusi yang komprehensif',
      'Tidak ada pemahaman mendalam tentang kebutuhan UMKM Indonesia',
    ],
    craft: {
      context: 'Target: UMKM Indonesia (warung, toko offline, kuliner, fashion)\nSkala: Bisa digunakan oleh 64 juta UMKM Indonesia\nKendala: Sebagian besar tidak melek teknologi, budget terbatas, smartphone is primary device\nEkosistem: Integrasi dengan WhatsApp, GoPay/OVO/DANA, Tokopedia/Shopee\nBahasa: Indonesia + dialek daerah utama',
      role: 'Kamu adalah Chief AI Officer yang pernah deploy AI solutions untuk 1 juta UMKM di Asia Tenggara bersama Google, Gojek, dan Grameen Bank.',
      action: 'Design sistem AI UMKM komprehensif yang mencakup: onboarding AI, fitur utama, arsitektur teknis, dan strategi implementasi.',
      format: 'Master Document:\n1. Executive Vision (1 halaman)\n2. User Journey Map (dari tidak kenal AI hingga power user)\n3. Feature Architecture (10 fitur prioritas)\n4. AI System Design:\n   a. Multi-agent system design\n   b. RAG knowledge base (regulasi UMKM, best practices)\n   c. Memory system untuk personalisasi\n   d. Tool integrations (MCP-based)\n5. Prompt Library (10 system prompts untuk berbagai agent)\n6. Implementation Roadmap (6 bulan)\n7. Success Metrics & KPI\n8. Risk & Mitigation',
      test: 'KRITERIA MASTER:\n✓ Solusi harus bisa digunakan oleh UMKM buta huruf teknologi\n✓ Dapat berjalan di smartphone dengan koneksi 3G\n✓ ROI terukur: minimal hemat 2 jam kerja/hari per UMKM\n✓ Skalabel ke 1 juta pengguna dalam 1 tahun\n✓ Comply dengan UU PDP No. 27/2022\n✓ Gunakan semua framework: CRAFT + Context Engineering + RAG + Memory + Agent + MCP\n✓ Prompt harus bisa langsung diimplementasikan, bukan konseptual belaka',
    },
    evaluationFocus: ['context', 'role', 'action', 'format', 'test', 'creativity'],
  },
];

/**
 * Mendapatkan data level berdasarkan nomor level
 * @param {number} num
 * @returns {Object|null}
 */
export function getLevelData(num) {
  return LEVELS.find(l => l.num === num) || null;
}

/**
 * Mendapatkan icon status level
 * @param {number} levelNum
 * @param {Object} progress
 * @returns {string}
 */
export function getLevelStatus(levelNum, progress) {
  if (progress.completedLevels?.includes(levelNum)) return '✅';
  if (levelNum === (progress.currentLevel || 1)) return '⚡';
  if (levelNum > (progress.currentLevel || 1)) return '🔒';
  return '⭕';
}
